import type { Metadata } from "next";
import { Inter, Cormorant_Garamond, Parisienne } from "next/font/google";
import "./globals.css";


const cormorantGaramond = Cormorant_Garamond({
      variable: "--font-cormorant-garamond",
      subsets: ["latin"]
})

const parisienne = Parisienne({
      variable: "--font-parisienne",
      subsets: ["latin"],
      weight: ["400"]
})

const inter = Inter({
      variable: "--font-inter",
      subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorantGaramond.variable} ${inter.variable} ${parisienne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}


/* 


  --font-inter: var(--font-inter);
  --font-cormorantGaramond: var(--font-cormorant-garamond);
  
  */